sudo: required
services:
  - docker

before_install:
  - docker build -t twh0008/solid-adventure -f Dockerfile.dev .

script:
  - docker run twh0008/solid-adventure npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "solid-adventure"
  env: "SolidAdventure-env"
  bucket_name: "elasticbeanstalk-us-east-2-033480132389"
  bucket_path: "solid-adventure"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
      secure: "$AWS_SECRET_KEY"